name: Mirror Odoo Enterprise

on:
  schedule:
    - cron: "17 * * * *"   # hourly
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UPSTREAM_URL: https://github.com/odoo/enterprise.git
      TARGET_URL: https://github.com/AlphaBaiter/enterprise.git
      ODOO_BRANCH: 19.0
    steps:
      - name: Prepare auth-safe remotes
        run: |
          set -euo pipefail
          mkdir -p mirror && cd mirror
          # Use token headers; avoids putting tokens in remotes or logs
          git init --bare
          git -c http.extraheader="Authorization: Bearer ${{ secrets.UPSTREAM_PAT }}" \
              fetch --prune --tags "${UPSTREAM_URL}" "+refs/*:refs/*"
          # Push mirror (branches+tags, delete removed upstream refs)
          git -c http.extraheader="Authorization: Bearer ${{ secrets.TARGET_PAT }}" \
              push --mirror --prune "${TARGET_URL}"
