name: Sync Odoo Enterprise (vendor branches)

on:
  schedule:
    - cron: "23 2 * * *"   # nightly
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  vendor_sync:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_URL: https://github.com/odoo/enterprise.git
      ODOO_BRANCH: 19.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch upstream branch and tags
        run: |
          set -euo pipefail
          git remote add upstream "${UPSTREAM_URL}" || true
          git -c http.extraheader="Authorization: Bearer ${{ secrets.UPSTREAM_PAT }}" \
            fetch --prune --tags upstream "+refs/heads/${ODOO_BRANCH}:refs/remotes/upstream/${ODOO_BRANCH}" "+refs/tags/*:refs/tags/*"

      - name: Update vendor branch (fast-forward)
        run: |
          set -euo pipefail
          git update-ref "refs/heads/vendor/${ODOO_BRANCH}" "refs/remotes/upstream/${ODOO_BRANCH}"
          git push origin "refs/heads/vendor/${ODOO_BRANCH}:refs/heads/vendor/${ODOO_BRANCH}"
          # Push tags too (add rules if you want only odoo/* tags)
          git push --tags origin
