name: Sync upstream (odoo/enterprise)

on:
  schedule:
    - cron: "23 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'  # secrets not available on PR from forks
    env:
      ODOO_BRANCH: 19.0
      UPSTREAM_URL: https://github.com/odoo/enterprise.git
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate UPSTREAM_PAT has repo access
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PAT }}
        run: |
          set -euo pipefail
          test -n "${UPSTREAM_PAT}" || { echo "UPSTREAM_PAT is not set"; exit 1; }
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${UPSTREAM_PAT}" \
            https://api.github.com/repos/odoo/enterprise)
          if [ "$code" != "200" ]; then
            echo "Token cannot access odoo/enterprise (HTTP $code). Check repo access/SSO/owner." >&2
            exit 1
          fi

      - name: Fetch upstream branch
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PAT }}
        run: |
          set -euo pipefail
          git remote add upstream "${UPSTREAM_URL}" || true
          git -c http.extraheader="AUTHORIZATION: bearer ${UPSTREAM_PAT}" \
            fetch --prune upstream \
              "+refs/heads/${ODOO_BRANCH}:refs/remotes/upstream/${ODOO_BRANCH}"
          # optional: tags
          # git -c http.extraheader="AUTHORIZATION: bearer ${UPSTREAM_PAT}" \
          #   fetch --prune --tags upstream "+refs/tags/*:refs/tags/*"

      - name: Fast-forward fork branch and push
        run: |
          set -euo pipefail
          TARGET="${ODOO_BRANCH}"   # or vendor/${ODOO_BRANCH}
          git checkout -B "${TARGET}"
          git reset --hard "refs/remotes/upstream/${ODOO_BRANCH}"
          git push origin "HEAD:refs/heads/${TARGET}"
          # optional: push tags
          # git push origin --tags
